"""empty message

Revision ID: 07d6032ca80f
Revises: 3e3d0e351907
Create Date: 2022-05-13 13:48:45.343842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '07d6032ca80f'
down_revision = '3e3d0e351907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profilepic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profilepic', postgresql.BYTEA(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
