""" pitch table

Revision ID: 3e3d0e351907
Revises: 9733fed3f945
Create Date: 2022-05-13 10:23:14.384342

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e3d0e351907'
down_revision = '9733fed3f945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profilepic',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profilepic',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###
