"""pitch table update

Revision ID: 9733fed3f945
Revises: 3b2465d4de76
Create Date: 2022-05-13 10:06:07.760172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9733fed3f945'
down_revision = '3b2465d4de76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profilepic',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profilepic',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###
